[package]
name = "msh-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
miette = { version = "7.2.0" }
thiserror = "1.0.59"
unicode-ident = "1.0.12"

[features]
default = ["fancy"]
fancy = ["miette/fancy"]

